### PR TITLE
Change output of 'Package Completed'

### PR DESCRIPTION
**Pull request by agam778**
image

### CODE REVIEW

**Comment by sarthakroy2002** [comment]
+1 from my side

**Review by redducc — APPROVED** [review]
Great

**Review by sarthakroy2002 — APPROVED** [review]

**Comment by redducc** [comment]
> This commit changed my life. Now i last twice as long in bed and my girlfriend is really amazed. I also know the reason of existence of humanity, and i have solved quantum physics to discover infinite universes. Thanks

Well 0*2 is still 0

**Comment by Dhruvgera** [comment]
> > This commit changed my life. Now i last twice as long in bed and my girlfriend is really amazed. I also know the reason of existence of humanity, and i have solved quantum physics to discover infinite universes. Thanks
> 
> Well 0*2 is still 0

Thanks for this beautiful reply, I have now fapped to you

**Pull request merged**
